title: <p align="center"> Darlin Soto </p>

logo: "images/images.jpeg"

description:
  <p align="center">
  <a href="Gato Gordito">LinkedIn</a> |
  <a href="">GitHub</a>
  </p>
  
  <p align="justify">
  I am Gato gordito :3.
  <br><br>
  I am developing statistical models for astronomical objects.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
